# shellcheck shell=bash
# Browser IDE: code-server + Continue configured against the proxy (fake code-server, see run.sh). Services are down here.
CONT="$TMP/.continue/config.yaml"
check "ide start: starts proxy and IDE" "IDE läuft +http://localhost:$IPT" < <(timeout 90 "$N" ide start)
grep -q '^IDE_ENABLED=1$' "$TMP/home/config" && pass "ide: enabled in the config" || fail "ide: enabled in the config"
check "ide: code-server bound to loopback" "fake code-server on 127.0.0.1:$IPT" < "$TMP/home/logs/code-server.log"
grep -q "^bind-addr: 127.0.0.1:$IPT$" "$TMP/home/code-server.yaml" && grep -q '^auth: password$' "$TMP/home/code-server.yaml" && pass "ide: code-server.yaml" || fail "ide: code-server.yaml"
[[ $(stat -c %a "$TMP/home/code-server.yaml") == 600 ]] && pass "ide: code-server.yaml perms 600" || fail "ide: code-server.yaml perms"
pw=$(timeout 10 "$N" ide password); [[ "$pw" =~ ^[A-Za-z0-9_-]{16,}$ ]] && grep -q "^password: $pw$" "$TMP/home/code-server.yaml" && pass "ide password: matches the config" || fail "ide password: matches the config"
grep -q '^# generated by nimctl' "$CONT" && grep -q 'model: nim-code' "$CONT" && grep -q "apiBase: http://127.0.0.1:$PP/v1" "$CONT" && grep -q 'apiKey: sk-nimctl-' "$CONT" && pass "ide: Continue config with proxy and master key" || fail "ide: Continue config"
grep -q 'model: nim-review' "$CONT" && pass "ide: review model offered" || fail "ide: review model offered"
grep -q 'roles: \[autocomplete\]' "$CONT" && fail "ide: autocomplete off by default" || pass "ide: autocomplete off by default"
[[ $(stat -c %a "$CONT") == 600 ]] && pass "ide: Continue config perms 600" || fail "ide: Continue config perms"
check "ide autocomplete on: warns about the rate limit" "Free Tier" < <(timeout 10 "$N" ide autocomplete on)
grep -q 'roles: \[autocomplete\]' "$CONT" && grep -q 'useLegacyCompletionsEndpoint: false' "$CONT" && pass "ide: autocomplete model written" || fail "ide: autocomplete model written"
timeout 10 "$N" ide autocomplete off >/dev/null; grep -q 'roles: \[autocomplete\]' "$CONT" && fail "ide: autocomplete removed" || pass "ide: autocomplete removed"
check "ide autocomplete: invalid argument exits 64" "ungültige Eingabe" < <(timeout 10 "$N" ide autocomplete sideways; echo "rc=$?")
timeout 10 "$N" ide autocomplete sideways >/dev/null 2>&1; assert "ide autocomplete: rc 64" [ $? -eq 64 ]
# a foreign Continue config is never overwritten without --force
printf 'name: mine\nversion: 1.0.0\nschema: v1\nmodels: []\n' >"$CONT"
check "ide config: foreign file kept" "nicht von nimctl" < <(timeout 10 "$N" ide config)
grep -q '^name: mine$' "$CONT" && pass "ide config: foreign content intact" || fail "ide config: foreign content intact"
check "ide config --force: overwrites" "Continue-Konfiguration" < <(timeout 10 "$N" ide config --force)
grep -q 'model: nim-code' "$CONT" && pass "ide config --force: nimctl content" || fail "ide config --force: nimctl content"
check "status: IDE row" "IDE +✓ läuft +:$IPT" < <(timeout 20 "$N" status)
check "status --json: ide block" '"ide":\{"enabled":true,"up":true' < <(timeout 20 "$N" status --json | jq -c .)
check "dashboard: footer lists v IDE" "Nutzen .*v IDE" < <(printf 'q\n' | timeout 30 "$N")
check "ide stop" "IDE gestoppt" < <(timeout 30 "$N" ide stop)
check "start: includes the IDE when enabled" "IDE läuft" < <(timeout 90 "$N" start)
check "stop: stops the IDE too" "IDE gestoppt" < <(timeout 30 "$N" stop)
check "status: IDE down" "IDE +✗ aus" < <(timeout 20 "$N" status)
check "ide password --reset" "neues IDE-Passwort" < <(timeout 10 "$N" ide password --reset)
pw2=$(timeout 10 "$N" ide password); [[ "$pw2" != "$pw" ]] && pass "ide password --reset: changed" || fail "ide password --reset: changed"
check "help: ide listed" "^  ide +.*code-server" < <(NIMCTL_LANG=en timeout 10 "$N" help)
