# shellcheck shell=bash
# uninstall: refuses without a terminal or --yes, shows the plan, removes command/completion/timer, keeps the PATH line;
# --keep-data leaves ~/.nimctl, --all removes it and calls the tool uninstallers (fake uv/npm here).
UH="$TMP/uhome"; UN="$UH/.nimctl"; rm -rf "$UH"; mkdir -p "$UH/.local/bin" "$UH/.local/lib/code-server-4.9/bin" "$UH/.continue" "$UN/logs" "$TMP/unbin"
cp "$N" "$UH/.local/bin/nimctl"; printf 'NVIDIA_API_KEY=nvapi-testkey\n' >"$UN/config"; printf '# generated by nimctl\nname: nimctl\n' >"$UH/.continue/config.yaml"
printf 'export PATH="$HOME/.local/bin:$PATH"\neval "$(nimctl completion bash)"\n' >"$UH/.bashrc"; printf 'eval "$(nimctl completion zsh)"\nalias ll="ls -l"\n' >"$UH/.zshrc"
printf '#!/usr/bin/env bash\necho "uv $*" >>"%s/uninstall-tools.log"\n' "$TMP" >"$TMP/unbin/uv"; printf '#!/usr/bin/env bash\necho "npm $*" >>"%s/uninstall-tools.log"\n' "$TMP" >"$TMP/unbin/npm"; printf '#!/usr/bin/env bash\nexit 0\n' >"$TMP/unbin/claude"; chmod +x "$TMP/unbin/uv" "$TMP/unbin/npm" "$TMP/unbin/claude"
U() { HOME="$UH" NIMCTL_HOME="$UN" PATH="$TMP/unbin:$PATH" NIMCTL_INTERACTIVE="${UI:-0}" timeout 60 "$UH/.local/bin/nimctl" uninstall "$@"; }
check "uninstall: needs --yes without a terminal" "kein Terminal – nimctl uninstall --yes" < <(U 2>&1)
[[ -x "$UH/.local/bin/nimctl" && -f "$UN/config" ]] && pass "uninstall: nothing removed without --yes" || fail "uninstall: nothing removed without --yes"
check "uninstall: unknown flag" "ungültig.*--foo" < <(U --foo 2>&1)
check "uninstall --keep-data --yes: plan and result" "Entfernt wird:.*bleibt: $UN.*Completion-Zeile aus ~/.bashrc entfernt.*Completion-Zeile aus ~/.zshrc entfernt.*PATH-Zeile in ~/.bashrc bleibt.*entfernt: $UH/.local/bin/nimctl.*nimctl ist entfernt" < <(U --keep-data --yes 2>&1 | tr '\n' ' ')
[[ ! -e "$UH/.local/bin/nimctl" ]] && pass "uninstall: command removed" || fail "uninstall: command removed"
[[ -f "$UN/config" ]] && pass "uninstall --keep-data: ~/.nimctl kept" || fail "uninstall --keep-data: ~/.nimctl kept"
grep -qx 'export PATH="$HOME/.local/bin:$PATH"' "$UH/.bashrc" && ! grep -q 'nimctl completion' "$UH/.bashrc" && ! grep -q 'nimctl completion' "$UH/.zshrc" && grep -qx 'alias ll="ls -l"' "$UH/.zshrc" && pass "uninstall: completion lines gone, PATH line and other lines kept" || fail "uninstall: rc files"
[[ -d "$UH/.local/lib/code-server-4.9" && -f "$UH/.continue/config.yaml" && ! -f "$TMP/uninstall-tools.log" ]] && pass "uninstall: tools untouched without --tools" || fail "uninstall: tools untouched without --tools"
cp "$N" "$UH/.local/bin/nimctl"
check "uninstall --all --yes: data, tools and Claude Code" "Werkzeuge: litellm, open-webui.*Claude Code \(npm.*entfernt: litellm open-webui code-server ~/.continue/config.yaml.*entfernt: claude.*entfernt: $UN " < <(U --all --yes 2>&1 | tr '\n' ' ')
[[ ! -e "$UN" && ! -e "$UH/.local/lib/code-server-4.9" && ! -f "$UH/.continue/config.yaml" ]] && pass "uninstall --all: ~/.nimctl, code-server and the Continue config removed" || fail "uninstall --all: removals"
check "uninstall --all: uv and npm called" "uv tool uninstall litellm.*uv tool uninstall open-webui.*npm uninstall -g @anthropic-ai/claude-code" < <(tr '\n' ' ' <"$TMP/uninstall-tools.log")
cp "$N" "$UH/.local/bin/nimctl"; mkdir -p "$UN"; printf 'x\n' >"$UN/config"; printf '# mine\nname: mine\n' >"$UH/.continue/config.yaml"
check "uninstall (interactive): every question answered no, then confirmed" "Daten in $UN löschen.*Werkzeuge deinstallieren.*Claude Code deinstallieren.*bleibt: $UN.*Wirklich entfernen\?.*nimctl ist entfernt" < <(printf 'n\nn\nn\ny\n' | UI=1 U 2>&1 | tr '\n' ' ')
[[ -f "$UN/config" && -f "$UH/.continue/config.yaml" && ! -e "$UH/.local/bin/nimctl" ]] && pass "uninstall (interactive): data and a foreign Continue config kept" || fail "uninstall (interactive): kept"
cp "$N" "$UH/.local/bin/nimctl"
check "uninstall (interactive): declined at the confirmation" "nichts geändert" < <(printf 'n\nn\nn\nn\n' | UI=1 U 2>&1)
[[ -x "$UH/.local/bin/nimctl" ]] && pass "uninstall: declined → nothing removed" || fail "uninstall: declined → nothing removed"
check "help: uninstall listed" "^  uninstall +.*--all" < <(NIMCTL_LANG=en timeout 10 "$N" help)
check "completion: uninstall flags" "uninstall\) COMPREPLY.*--keep-data" < <(timeout 10 "$N" completion bash)
rm -rf "$UH" "$TMP/unbin" "$TMP/uninstall-tools.log"
