# ── Throttle & chain routing: the LiteLLM hook nimctl writes ──────────────────────────────────────────────────
# $NIM_DIR/nimctl_hooks.py is one LiteLLM callback with three jobs:
#  1. Budget: NVIDIA's free tier allows roughly 40 requests per minute per key (unpublished, observed), across all
#     models. One token bucket for everything that goes to NVIDIA through the proxy: a request beyond the budget waits
#     for the next free slot instead of failing; after NIMCTL_RPM_MAX_WAIT seconds it is refused with Retry-After. An
#     upstream 429 shrinks the budget for five minutes. Requests routed to a pool provider do not touch the bucket.
#  2. Chain routing: every slot is a chain of ranks (model groups nim-<slot>, nim-<slot>-r2, …, see write_litellm_yaml);
#     a request for nim-<slot> is sent to the best rank that is not cooling down.
#  3. Cooldowns: a rank that fails (stall, 429, 5xx – also mid-stream, where LiteLLM's own cooldown does not apply to a
#     single-deployment group) is registered in LiteLLM's cooldown cache, so the fallback chain of the running request
#     and every later request skip it: RateLimitError starts at NIMCTL_COOLDOWN_RATELIMIT (20 s), timeouts/5xx at
#     NIMCTL_COOLDOWN (120 s), doubling per consecutive failure up to 30 min, cleared by a success.
# State for the dashboard and the web UI: $NIM_DIR/rpm.json (budget) and $NIM_DIR/health.json (cooldowns).
T_de+=(
  [thr_line]="Budget   %s/min · %s frei · %s wartend · %s gebremst%s" [thr_avg]=" (Ø %s s)" [thr_penalty]=" · gedrosselt nach 429 bis %s"
  [thr_rejected]=" · %s abgewiesen" [thr_cool]="Pausiert %s" [thr_cool_item]="%s (%s, bis %s)"
)
T_en+=(
  [thr_line]="Budget   %s/min · %s free · %s waiting · %s throttled%s" [thr_avg]=" (avg %s s)" [thr_penalty]=" · reduced after 429 until %s"
  [thr_rejected]=" · %s rejected" [thr_cool]="Paused   %s" [thr_cool_item]="%s (%s, until %s)"
)
throttle_env() { # the hook's settings, exported for the proxy process
  export NIMCTL_RPM="${NIMCTL_RPM:-36}" NIMCTL_RPM_MAX_WAIT="${NIMCTL_RPM_MAX_WAIT:-30}" NIMCTL_RPM_STATE="$NIM_DIR/rpm.json"
  export NIMCTL_CHAINS="$NIM_DIR/chains.json" NIMCTL_HEALTH="$NIM_DIR/health.json" NIMCTL_COOLDOWN="$COOLDOWN" NIMCTL_COOLDOWN_RATELIMIT="${NIMCTL_COOLDOWN_RATELIMIT:-20}"
  export PYTHONPATH="$NIM_DIR${PYTHONPATH:+:$PYTHONPATH}"
}
write_litellm_hooks() { # $NIM_DIR/nimctl_hooks.py – rewritten on every proxy start
  cat >"$NIM_DIR/nimctl_hooks.py.tmp" <<'HOOKS_PY'
# generated by nimctl – budget, chain routing and cooldowns for the LiteLLM proxy (see src/25-throttle.sh)
import asyncio
import json
import os
import time

from litellm.integrations.custom_logger import CustomLogger

try:
    from fastapi import HTTPException
except ImportError:  # pragma: no cover – the proxy always ships fastapi
    class HTTPException(Exception):  # type: ignore[no-redef]
        def __init__(self, status_code, detail="", headers=None):
            super().__init__(detail); self.status_code = status_code; self.detail = detail; self.headers = headers or {}

RPM = max(1, int(os.environ.get("NIMCTL_RPM", "36") or 36))
MAX_WAIT = float(os.environ.get("NIMCTL_RPM_MAX_WAIT", "30") or 30)
STATE = os.environ.get("NIMCTL_RPM_STATE", "")
HEALTH = os.environ.get("NIMCTL_HEALTH", "")
CHAINS_FILE = os.environ.get("NIMCTL_CHAINS", "")
COOLDOWN = float(os.environ.get("NIMCTL_COOLDOWN", "120") or 120)   # first timeout/5xx; doubles per consecutive failure
COOLDOWN_RATELIMIT = float(os.environ.get("NIMCTL_COOLDOWN_RATELIMIT", "20") or 20)  # first 429 / RateLimitError
COOLDOWN_MAX = 1800.0
PENALTY_SECONDS = 300.0


def _load_chains():
    """{"code": ["nim-code", "nim-code-r2", …], …, "nim": [groups that are NVIDIA deployments], "models": {group: id}}"""
    try:
        with open(CHAINS_FILE) as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


class Throttle(CustomLogger):
    """Budget for NVIDIA, best-healthy-rank routing for the slots, cooldowns LiteLLM honours."""

    def __init__(self):
        super().__init__()
        self.capacity = float(RPM)      # the configured budget per minute
        self.limit = float(RPM)         # the current budget (shrinks after upstream 429s)
        self.tokens = float(RPM)        # may go negative: that is the queue of reserved slots
        self.last = time.monotonic()
        self.penalty_until = 0.0
        self.grow_at = 0.0
        self.lock = asyncio.Lock()
        self.waiting = 0
        self.throttled = 0
        self.rejected = 0
        self.upstream_429 = 0
        self.wait_total = 0.0
        chains = _load_chains()
        self.chains = {k: v for k, v in chains.items() if k not in ("nim", "models")}   # slot → ordered groups
        self.rank = {g: (slot, i) for slot, groups in self.chains.items() for i, g in enumerate(groups)}
        self.nim = set(chains.get("nim") or [])
        self.models = chains.get("models") or {}
        self.cool = {}      # group → (until_monotonic, reason)
        self.fails = {}     # group → consecutive failures
        self.recent = {}    # group → monotonic time of the last counted failure
        self.routed = 0
        self._save()

    # ── routing ───────────────────────────────────────────────────────────────────────────────────
    def _route(self, model):
        """The requested group, or the first rank at or after it that is not cooling down."""
        if model not in self.rank:
            return model
        slot, i = self.rank[model]
        now = time.monotonic()
        for g in self.chains[slot][i:]:
            until = self.cool.get(g, (0.0, ""))[0]
            if until <= now:
                return g
        return model

    # ── budget ────────────────────────────────────────────────────────────────────────────────────
    def _refill(self):
        now = time.monotonic()
        self.tokens = min(self.limit, self.tokens + (now - self.last) * self.limit / 60.0)
        self.last = now
        if self.limit < self.capacity and now >= self.penalty_until and now >= self.grow_at:
            self.limit = min(self.capacity, self.limit + self.capacity * 0.1)   # recover 10 % per minute
            self.grow_at = now + 60.0

    def _wait_for_slot(self):
        """Reserve one slot; returns how long the caller has to wait before using it."""
        self._refill()
        wait = 0.0 if self.tokens >= 1 else (1.0 - self.tokens) * 60.0 / self.limit
        if wait > MAX_WAIT:
            return None
        self.tokens -= 1.0
        return wait

    async def async_pre_call_hook(self, user_api_key_dict, cache, data, call_type):
        model = str((data or {}).get("model", "?"))
        target = self._route(model)
        if target != model:
            data["model"] = target
            self.routed += 1
            print(f"nimctl chain: {model} → {target} ({self.models.get(target, '?')})", flush=True)
        if self.nim and target not in self.nim and target in self.rank:
            return data                                   # a pool provider: not NVIDIA's budget
        async with self.lock:
            wait = self._wait_for_slot()
            if wait is None:
                self.rejected += 1
                retry = int((1.0 - self.tokens) * 60.0 / self.limit) + 1
                self._save()
                print(f"nimctl throttle: rejected {model}, budget {self.limit:.0f}/min exhausted, retry after {retry}s", flush=True)
                raise HTTPException(status_code=429, detail=f"nimctl throttle: budget of {self.limit:.0f} requests/min exhausted, retry after {retry}s",
                                    headers={"Retry-After": str(retry)})
            if wait > 0:
                self.throttled += 1
                self.wait_total += wait
                self.waiting += 1
        if wait > 0:
            print(f"nimctl throttle: waited {wait:.1f}s ({model}, budget {self.limit:.0f}/min)", flush=True)
            self._save()
            try:
                await asyncio.sleep(wait)
            finally:
                self.waiting -= 1
        self._save()
        return data

    # ── cooldowns ─────────────────────────────────────────────────────────────────────────────────
    @staticmethod
    def _group_and_id(kwargs):
        lp = (kwargs or {}).get("litellm_params") or {}
        meta = lp.get("metadata") or {}
        return meta.get("model_group"), (lp.get("model_info") or {}).get("id")

    def _tell_router(self, model_id, exc, seconds):
        """Register the cooldown with LiteLLM's router, so its fallback chains skip the rank too."""
        try:
            from litellm.proxy import proxy_server
            router = getattr(proxy_server, "llm_router", None)
            if router is not None and model_id:
                router.cooldown_cache.add_deployment_to_cooldown(model_id=model_id, original_exception=exc,
                                                                 exception_status=getattr(exc, "status_code", 500) or 500, cooldown_time=seconds)
        except Exception as e:  # never let bookkeeping break a request
            print(f"nimctl chain: could not register cooldown: {e}", flush=True)

    async def async_log_failure_event(self, kwargs, response_obj, start_time, end_time):
        group, model_id = self._group_and_id(kwargs)
        if group not in self.rank:
            return
        exc = (kwargs or {}).get("exception")
        if group in self.recent and time.monotonic() - self.recent[group] < 5.0:
            return                                       # the same failure reported twice (the stream and the fallback attempt)
        self.recent[group] = time.monotonic()
        n = self.fails.get(group, 0) + 1
        self.fails[group] = n
        reason = type(exc).__name__ if exc is not None else "error"
        code = getattr(exc, "status_code", None) if exc is not None else None
        base = COOLDOWN_RATELIMIT if (code == 429 or "RateLimit" in reason) else COOLDOWN
        seconds = min(base * (2 ** (n - 1)), COOLDOWN_MAX)
        self.cool[group] = (time.monotonic() + seconds, reason)
        self._tell_router(model_id, exc if isinstance(exc, Exception) else Exception(reason), seconds)
        print(f"nimctl chain: {group} ({self.models.get(group, '?')}) failed with {reason}, paused {int(seconds)}s (failure {n})", flush=True)
        self._save()

    async def async_log_success_event(self, kwargs, response_obj, start_time, end_time):
        group, _ = self._group_and_id(kwargs)
        if group in self.rank and (self.fails.get(group) or group in self.cool):
            self.fails.pop(group, None)
            self.cool.pop(group, None)
            self._save()

    async def async_post_call_failure_hook(self, request_data, original_exception, user_api_key_dict=None, *args, **kwargs):
        code = getattr(original_exception, "status_code", None)
        name = type(original_exception).__name__
        model = str((request_data or {}).get("model", ""))
        if (code == 429 or "RateLimit" in name) and (not self.nim or model in self.nim or model not in self.rank):
            async with self.lock:
                self.upstream_429 += 1
                self.limit = max(self.capacity * 0.5, self.limit * 0.8)
                self.penalty_until = time.monotonic() + PENALTY_SECONDS
                self.grow_at = self.penalty_until
                self.tokens = min(self.tokens, 0.0)
                self._save()
            print(f"nimctl throttle: upstream 429, budget reduced to {self.limit:.0f}/min for {int(PENALTY_SECONDS / 60)} min", flush=True)

    # ── state files ───────────────────────────────────────────────────────────────────────────────
    def _save(self):
        now = time.monotonic()
        if STATE:
            state = {
                "rpm": int(self.capacity), "budget": round(self.limit), "free": max(0, int(self.tokens)),
                "waiting": self.waiting, "throttled": self.throttled, "rejected": self.rejected, "upstream_429": self.upstream_429,
                "avg_wait": round(self.wait_total / self.throttled, 1) if self.throttled else 0.0,
                "penalty_until": int(time.time() + (self.penalty_until - now)) if self.penalty_until > now else 0,
                "updated": int(time.time()),
            }
            self._write(STATE, state)
        if HEALTH:
            cool = {g: {"model": self.models.get(g, ""), "slot": self.rank[g][0], "rank": self.rank[g][1] + 1, "reason": r,
                        "until": int(time.time() + (u - now)), "fails": self.fails.get(g, 0)}
                    for g, (u, r) in self.cool.items() if u > now and g in self.rank}
            self._write(HEALTH, {"cooldown": cool, "routed": self.routed, "updated": int(time.time())})

    @staticmethod
    def _write(path, obj):
        try:
            tmp = path + ".tmp"
            with open(tmp, "w") as f:
                json.dump(obj, f)
            os.replace(tmp, path)
        except OSError:
            pass


throttle = Throttle()
HOOKS_PY
  chmod 600 "$NIM_DIR/nimctl_hooks.py.tmp"; mv "$NIM_DIR/nimctl_hooks.py.tmp" "$NIM_DIR/nimctl_hooks.py"
}
throttle_line() { # one dashboard line from rpm.json, only while the proxy is fresh (written within the last 2 minutes)
  local f="$NIM_DIR/rpm.json"; [[ -s "$f" ]] || return 1
  local budget free waiting throttled avg rejected penalty updated
  IFS=$'\t' read -r _ budget free waiting throttled avg rejected penalty updated < <(jq -r '[.rpm,.budget,.free,.waiting,.throttled,.avg_wait,.rejected,.penalty_until,.updated] | @tsv' "$f" 2>/dev/null) || return 1
  [[ "$updated" =~ ^[0-9]+$ ]] && (( $(date +%s) - updated < 120 )) || return 1
  local extra=""; (( throttled > 0 )) && extra+=$(tf thr_avg "$avg"); (( rejected > 0 )) && extra+=$(tf thr_rejected "$rejected")
  [[ "$penalty" =~ ^[0-9]+$ ]] && (( penalty > 0 )) && extra+=$(tf thr_penalty "$(fmt_time "$penalty" '+%H:%M')")
  tf thr_line "$budget" "$free" "$waiting" "$throttled" "$extra"
}
cooldown_line() { # one dashboard line from health.json: the ranks that are paused right now (empty → returns 1)
  local f="$NIM_DIR/health.json" items="" line; [[ -s "$f" ]] || return 1
  while IFS=$'\t' read -r slot rank model reason until; do [[ -n "$slot" ]] || continue; items+="${items:+ · }$(tf thr_cool_item "$slot #$rank $(trunc "$model" 44)" "$reason" "$(fmt_time "$until" '+%H:%M')")"; done \
    < <(jq -r --argjson now "$(date +%s)" '.cooldown | to_entries[] | select(.value.until > $now) | [.value.slot, .value.rank, .value.model, .value.reason, .value.until] | @tsv' "$f" 2>/dev/null | sort)
  [[ -n "$items" ]] || return 1; tf thr_cool "$items"
}
