# ── Throttle: never let the NVIDIA key run into its per-minute limit ──────────────────────────────────────────
# NVIDIA's free tier allows roughly 40 requests per minute per key (unpublished, observed), across all models.
# $NIM_DIR/nimctl_hooks.py is a LiteLLM pre-call hook with one token bucket for everything that goes through the
# proxy (Claude Code, the IDE, the chat, the search's query generation): a request that would exceed the budget
# waits for the next free slot instead of failing; only after NIMCTL_RPM_MAX_WAIT seconds it is refused locally
# with Retry-After. An upstream 429 shrinks the budget for five minutes, then it grows back. The hook writes its
# state to $NIM_DIR/rpm.json for the dashboard. Probes, watch and bench talk to NVIDIA directly: the default
# budget of 36 leaves them room.
T_de+=(
  [thr_line]="Budget   %s/min · %s frei · %s wartend · %s gebremst%s" [thr_avg]=" (Ø %s s)" [thr_penalty]=" · gedrosselt nach 429 bis %s"
  [thr_rejected]=" · %s abgewiesen"
)
T_en+=(
  [thr_line]="Budget   %s/min · %s free · %s waiting · %s throttled%s" [thr_avg]=" (avg %s s)" [thr_penalty]=" · reduced after 429 until %s"
  [thr_rejected]=" · %s rejected"
)
throttle_env() { # the hook's settings, exported for the proxy process
  export NIMCTL_RPM="${NIMCTL_RPM:-36}" NIMCTL_RPM_MAX_WAIT="${NIMCTL_RPM_MAX_WAIT:-30}" NIMCTL_RPM_STATE="$NIM_DIR/rpm.json"
  export PYTHONPATH="$NIM_DIR${PYTHONPATH:+:$PYTHONPATH}"
}
write_litellm_hooks() { # $NIM_DIR/nimctl_hooks.py – rewritten on every proxy start
  cat >"$NIM_DIR/nimctl_hooks.py.tmp" <<'HOOKS_PY'
# generated by nimctl – request throttle for the LiteLLM proxy (see src/25-throttle.sh)
import asyncio
import json
import os
import time

from litellm.integrations.custom_logger import CustomLogger

try:
    from fastapi import HTTPException
except ImportError:  # pragma: no cover – the proxy always ships fastapi
    class HTTPException(Exception):  # type: ignore[no-redef]
        def __init__(self, status_code, detail="", headers=None):
            super().__init__(detail); self.status_code = status_code; self.detail = detail; self.headers = headers or {}

RPM = max(1, int(os.environ.get("NIMCTL_RPM", "36") or 36))
MAX_WAIT = float(os.environ.get("NIMCTL_RPM_MAX_WAIT", "30") or 30)
STATE = os.environ.get("NIMCTL_RPM_STATE", "")
PENALTY_SECONDS = 300.0


class Throttle(CustomLogger):
    """One token bucket for every request the proxy forwards: wait for a slot instead of failing."""

    def __init__(self):
        super().__init__()
        self.capacity = float(RPM)      # the configured budget per minute
        self.limit = float(RPM)         # the current budget (shrinks after upstream 429s)
        self.tokens = float(RPM)        # may go negative: that is the queue of reserved slots
        self.last = time.monotonic()
        self.penalty_until = 0.0
        self.grow_at = 0.0
        self.lock = asyncio.Lock()
        self.waiting = 0
        self.throttled = 0
        self.rejected = 0
        self.upstream_429 = 0
        self.wait_total = 0.0
        self._save()

    def _refill(self):
        now = time.monotonic()
        self.tokens = min(self.limit, self.tokens + (now - self.last) * self.limit / 60.0)
        self.last = now
        if self.limit < self.capacity and now >= self.penalty_until and now >= self.grow_at:
            self.limit = min(self.capacity, self.limit + self.capacity * 0.1)   # recover 10 % per minute
            self.grow_at = now + 60.0

    def _wait_for_slot(self):
        """Reserve one slot; returns how long the caller has to wait before using it."""
        self._refill()
        wait = 0.0 if self.tokens >= 1 else (1.0 - self.tokens) * 60.0 / self.limit
        if wait > MAX_WAIT:
            return None
        self.tokens -= 1.0
        return wait

    async def async_pre_call_hook(self, user_api_key_dict, cache, data, call_type):
        model = str((data or {}).get("model", "?"))
        async with self.lock:
            wait = self._wait_for_slot()
            if wait is None:
                self.rejected += 1
                retry = int((1.0 - self.tokens) * 60.0 / self.limit) + 1
                self._save()
                print(f"nimctl throttle: rejected {model}, budget {self.limit:.0f}/min exhausted, retry after {retry}s", flush=True)
                raise HTTPException(status_code=429, detail=f"nimctl throttle: budget of {self.limit:.0f} requests/min exhausted, retry after {retry}s",
                                    headers={"Retry-After": str(retry)})
            if wait > 0:
                self.throttled += 1
                self.wait_total += wait
                self.waiting += 1
        if wait > 0:
            print(f"nimctl throttle: waited {wait:.1f}s ({model}, budget {self.limit:.0f}/min)", flush=True)
            self._save()
            try:
                await asyncio.sleep(wait)
            finally:
                self.waiting -= 1
        self._save()
        return data

    async def async_post_call_failure_hook(self, request_data, original_exception, user_api_key_dict=None, *args, **kwargs):
        code = getattr(original_exception, "status_code", None)
        name = type(original_exception).__name__
        if code == 429 or "RateLimit" in name:
            async with self.lock:
                self.upstream_429 += 1
                self.limit = max(self.capacity * 0.5, self.limit * 0.8)
                self.penalty_until = time.monotonic() + PENALTY_SECONDS
                self.grow_at = self.penalty_until
                self.tokens = min(self.tokens, 0.0)
                self._save()
            print(f"nimctl throttle: upstream 429, budget reduced to {self.limit:.0f}/min for {int(PENALTY_SECONDS / 60)} min", flush=True)

    def _save(self):
        if not STATE:
            return
        now = time.monotonic()
        state = {
            "rpm": int(self.capacity), "budget": round(self.limit), "free": max(0, int(self.tokens)),
            "waiting": self.waiting, "throttled": self.throttled, "rejected": self.rejected, "upstream_429": self.upstream_429,
            "avg_wait": round(self.wait_total / self.throttled, 1) if self.throttled else 0.0,
            "penalty_until": int(time.time() + (self.penalty_until - now)) if self.penalty_until > now else 0,
            "updated": int(time.time()),
        }
        try:
            tmp = STATE + ".tmp"
            with open(tmp, "w") as f:
                json.dump(state, f)
            os.replace(tmp, STATE)
        except OSError:
            pass


throttle = Throttle()
HOOKS_PY
  chmod 600 "$NIM_DIR/nimctl_hooks.py.tmp"; mv "$NIM_DIR/nimctl_hooks.py.tmp" "$NIM_DIR/nimctl_hooks.py"
}
throttle_line() { # one dashboard line from rpm.json, only while the proxy is fresh (written within the last 2 minutes)
  local f="$NIM_DIR/rpm.json"; [[ -s "$f" ]] || return 1
  local budget free waiting throttled avg rejected penalty updated
  IFS=$'\t' read -r _ budget free waiting throttled avg rejected penalty updated < <(jq -r '[.rpm,.budget,.free,.waiting,.throttled,.avg_wait,.rejected,.penalty_until,.updated] | @tsv' "$f" 2>/dev/null) || return 1
  [[ "$updated" =~ ^[0-9]+$ ]] && (( $(date +%s) - updated < 120 )) || return 1
  local extra=""; (( throttled > 0 )) && extra+=$(tf thr_avg "$avg"); (( rejected > 0 )) && extra+=$(tf thr_rejected "$rejected")
  [[ "$penalty" =~ ^[0-9]+$ ]] && (( penalty > 0 )) && extra+=$(tf thr_penalty "$(fmt_time "$penalty" '+%H:%M')")
  tf thr_line "$budget" "$free" "$waiting" "$throttled" "$extra"
}
