# ── Browser IDE: code-server (VS Code in the browser) with the Continue extension on the proxy ─────────────
# Files: $NIM_DIR/code-server.yaml (bind address, password), $NIM_DIR/ide-data (user data, extensions),
# ~/.continue/config.yaml (Continue's global config; written only when absent or generated by nimctl).
T_de+=(
  [k_v]="IDE" [h_ide]="VS Code im Browser (code-server + Continue) auf dem Proxy: nimctl ide [open|start|stop|disable|password|config|autocomplete on|off|install]"
  [ide_installing]="installiere code-server (~150 MB) … " [ide_ext]="installiere Extension %s … " [ide_enabled]="IDE aktiviert – nimctl start startet sie mit"
  [ide_url]="IDE: http://localhost:%s  · Passwort: nimctl ide password" [ide_pw_reset]="neues IDE-Passwort gesetzt – Neustart: nimctl ide stop && nimctl ide"
  [ide_cfg]="Continue-Konfiguration: %s" [ide_cfg_kept]="%s stammt nicht von nimctl – bleibt unverändert (nimctl ide config --force überschreibt)"
  [ide_ac_on]="Autocomplete an (Modell fast) – Achtung: viele Anfragen pro Minute auf dem Free Tier" [ide_ac_off]="Autocomplete aus"
  [ide_models]="Modelle in der IDE: code, fast%s – Continue liest die Konfiguration automatisch neu" [ide_no_proxy]="Proxy läuft nicht – die IDE braucht ihn"
  [ide_disabled]="IDE deaktiviert – start/stop/restart lassen sie aus; wieder an: nimctl ide"
)
T_en+=(
  [k_v]="IDE" [h_ide]="VS Code in the browser (code-server + Continue) on the proxy: nimctl ide [open|start|stop|disable|password|config|autocomplete on|off|install]"
  [ide_installing]="installing code-server (~150 MB) … " [ide_ext]="installing extension %s … " [ide_enabled]="IDE enabled – nimctl start starts it too"
  [ide_url]="IDE: http://localhost:%s  · password: nimctl ide password" [ide_pw_reset]="new IDE password set – restart: nimctl ide stop && nimctl ide"
  [ide_cfg]="Continue configuration: %s" [ide_cfg_kept]="%s was not written by nimctl – left untouched (nimctl ide config --force overwrites)"
  [ide_ac_on]="autocomplete on (fast model) – careful: many requests per minute on the free tier" [ide_ac_off]="autocomplete off"
  [ide_models]="models in the IDE: code, fast%s – Continue reloads the configuration automatically" [ide_no_proxy]="proxy is not running – the IDE needs it"
  [ide_disabled]="IDE disabled – start/stop/restart leave it out; back on: nimctl ide"
)
IDE_MARK="# generated by nimctl"
ide_continue_dir() { printf '%s' "${CONTINUE_GLOBAL_DIR:-$HOME/.continue}"; }
ide_write_config() { # ide_write_config [--force] – code-server.yaml (always) and Continue's config.yaml (ours or absent)
  mkdir -p "$NIM_DIR/ide-data/extensions"
  printf 'bind-addr: %s:%s\nauth: password\npassword: %s\ncert: false\n' "$BIND" "$IDE_PORT" "$IDE_PASSWORD" >"$NIM_DIR/code-server.yaml.tmp"
  chmod 600 "$NIM_DIR/code-server.yaml.tmp"; mv "$NIM_DIR/code-server.yaml.tmp" "$NIM_DIR/code-server.yaml"
  local dir f base="http://127.0.0.1:$PROXY_PORT/v1"; dir=$(ide_continue_dir); f="$dir/config.yaml"; [[ -d "$dir" ]] || { mkdir -p "$dir"; chmod 700 "$dir"; }
  if [[ -f "$f" && "${1:-}" != --force ]] && ! grep -qF "$IDE_MARK" "$f"; then info "$(tf ide_cfg_kept "$f")"; return 0; fi
  local ctx="${NIMCTL_IDE_CONTEXT:-32768}" more=""
  {
    printf '%s – rewritten on every `nimctl ide` start; remove this line to keep your own edits\nname: nimctl\nversion: 1.0.0\nschema: v1\nmodels:\n' "$IDE_MARK"
    printf '  - name: "code · %s"\n    provider: openai\n    model: nim-code\n    apiBase: %s\n    apiKey: %s\n    roles: [chat, edit, apply]\n    capabilities: [tool_use]\n    defaultCompletionOptions: { contextLength: %s, maxTokens: 8192 }\n' "$MODEL_CODE" "$base" "$MASTER_KEY" "$ctx"
    printf '  - name: "fast · %s"\n    provider: openai\n    model: nim-fast\n    apiBase: %s\n    apiKey: %s\n    roles: [chat]\n    defaultCompletionOptions: { contextLength: %s, maxTokens: 4096 }\n' "$MODEL_FAST" "$base" "$MASTER_KEY" "$ctx"
    if [[ -n "$MODEL_REVIEW" ]]; then more=", review"
      printf '  - name: "review · %s"\n    provider: openai\n    model: nim-review\n    apiBase: %s\n    apiKey: %s\n    roles: [chat]\n    capabilities: [tool_use]\n    defaultCompletionOptions: { contextLength: %s, maxTokens: 8192 }\n' "$MODEL_REVIEW" "$base" "$MASTER_KEY" "$ctx"; fi
    if [[ "$IDE_AUTOCOMPLETE" == 1 ]]; then more+=", autocomplete"
      printf '  - name: "autocomplete · %s"\n    provider: openai\n    model: nim-fast\n    apiBase: %s\n    apiKey: %s\n    roles: [autocomplete]\n    useLegacyCompletionsEndpoint: false\n    autocompleteOptions: { debounceDelay: 500, maxPromptTokens: 1024, onlyMyCode: true }\n' "$MODEL_FAST" "$base" "$MASTER_KEY"; fi
    printf 'context:\n  - provider: code\n  - provider: currentFile\n  - provider: open\n  - provider: diff\n  - provider: terminal\n  - provider: problems\n  - provider: folder\n'
  } >"$f.tmp"; chmod 600 "$f.tmp"; mv "$f.tmp" "$f"
  info "$(tf ide_cfg "$f")"; info "$(tf ide_models "$more")"
}
inst_codeserver() { # standalone install into ~/.local plus the Continue extension (and NIMCTL_IDE_EXTENSIONS)
  mkdir -p "$NIM_DIR/ide-data/extensions"
  if ! has code-server; then
    printf "  %s" "$(t ide_installing)"
    if curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix="$HOME/.local" >"$LOG_DIR/code-server-install.log" 2>&1; then printf "%s\n" "$OK"; else printf "%s\n" "$NO"; bad "$(tf inst_fail code-server) → $LOG_DIR/code-server-install.log"; return 1; fi
    if ! has code-server; then local b; b=$(ls -d "$HOME/.local/lib"/code-server-*/bin/code-server 2>/dev/null | tail -n1); [[ -n "$b" ]] && { mkdir -p "$HOME/.local/bin"; ln -sf "$b" "$HOME/.local/bin/code-server"; }; fi
    has code-server || { bad "$(tf inst_fail code-server)"; return 1; }
  fi
  local ext; for ext in Continue.continue ${NIMCTL_IDE_EXTENSIONS:-}; do
    printf "  %s" "$(tf ide_ext "$ext")"
    if code-server --extensions-dir "$NIM_DIR/ide-data/extensions" --user-data-dir "$NIM_DIR/ide-data" --install-extension "$ext" >>"$LOG_DIR/code-server-install.log" 2>&1; then printf "%s\n" "$OK"; else printf "%s\n" "$NO"; warn "$(tf inst_fail "$ext") → $LOG_DIR/code-server-install.log"; fi
  done
  [[ -n "$IDE_PASSWORD" ]] || IDE_PASSWORD=$(gen_secret | head -c 24)
  IDE_ENABLED=1; save_conf; ok "$(t ide_enabled)"
}
ide_ensure() { # installed, proxy up, code-server up – and only then enabled for start/stop/restart and systemd
  has code-server || { bad "$(tf svc_missing code-server)"; info "→ nimctl ide install"; return 1; }
  svc_running proxy || { info "$(t proxy_starting)"; start_proxy || { bad "$(t ide_no_proxy)"; return 1; }; }
  svc_running ide || start_ide || return 1
  [[ "$IDE_ENABLED" == 1 ]] || { IDE_ENABLED=1; save_conf; }
}
ide_disable() { # stop it, take it out of start/stop/restart and systemd; the installation and the configs stay
  if has systemctl && [[ -f "$(unit_dir)/nimctl-ide.service" ]]; then systemctl --user disable --now nimctl-ide 2>/dev/null; rm -f "$(unit_dir)/nimctl-ide.service"; systemctl --user daemon-reload 2>/dev/null; fi
  stop_svc ide; IDE_ENABLED=0; save_conf; ok "$(t ide_disabled)"
}
cmd_ide() { # cmd_ide [open|start|stop|disable|password [--reset]|config [--force]|autocomplete on|off|install]
  local sub="${1:-open}"; (( $# )) && shift
  case "$sub" in
    install) inst_codeserver;;
    open)    ide_ensure || return 1; ok "$(tf ide_url "$IDE_PORT")"; open_url "http://localhost:$IDE_PORT" || info "→ http://localhost:$IDE_PORT";;
    start)   ide_ensure;;
    stop)    stop_svc ide;;
    disable) ide_disable;;
    password) if [[ "${1:-}" == --reset ]]; then IDE_PASSWORD=$(gen_secret | head -c 24); save_conf; ide_write_config >/dev/null; ok "$(t ide_pw_reset)"; fi
              [[ -n "$IDE_PASSWORD" ]] || { IDE_PASSWORD=$(gen_secret | head -c 24); save_conf; }; printf '%s\n' "$IDE_PASSWORD";;
    config)  [[ -n "$IDE_PASSWORD" ]] || { IDE_PASSWORD=$(gen_secret | head -c 24); save_conf; }; ide_write_config "${1:-}";;
    autocomplete) case "${1:-}" in on) IDE_AUTOCOMPLETE=1; save_conf; ide_write_config && warn "$(t ide_ac_on)";; off) IDE_AUTOCOMPLETE=0; save_conf; ide_write_config && ok "$(t ide_ac_off)";; *) bad "$(t invalid): ${1:-}"; return 64;; esac;;
    *) bad "$(t unknown): $sub"; return 64;;
  esac
}
dash_register v cmd_ide k_v use
