# ── Browser IDE: code-server (VS Code in the browser) with the Continue extension on the proxy ─────────────
# Files: $NIM_DIR/code-server.yaml (bind address, password), $NIM_DIR/ide-data (user data, extensions),
# $NIM_DIR/mcp/shell.py (shell tool for Continue's agent mode: its own terminal tool returns no output in code-server),
# $NIM_DIR/ide-workspace (the project folder the IDE opens and the shell tool runs in),
# ~/.continue/config.yaml (Continue's global config; written only when absent or generated by nimctl).
T_de+=(
  [k_v]="IDE" [h_ide]="VS Code im Browser (code-server + Continue) auf dem Proxy: nimctl ide [Ordner|open [Ordner]|start|stop|disable|password|config|autocomplete on|off|install]"
  [ide_installing]="installiere code-server (~150 MB) … " [ide_ext]="installiere Extension %s … " [ide_enabled]="IDE aktiviert – nimctl start startet sie mit"
  [ide_url]="IDE: http://localhost:%s  · Passwort: nimctl ide password" [ide_pw_reset]="neues IDE-Passwort gesetzt – Neustart: nimctl ide stop && nimctl ide"
  [ide_cfg]="Continue-Konfiguration: %s" [ide_cfg_kept]="%s stammt nicht von nimctl – bleibt unverändert (nimctl ide config --force überschreibt)"
  [ide_ac_on]="Autocomplete an (Modell fast) – Achtung: viele Anfragen pro Minute auf dem Free Tier" [ide_ac_off]="Autocomplete aus"
  [ide_models]="Modelle in der IDE: code, fast%s – Continue liest die Konfiguration automatisch neu" [ide_no_proxy]="Proxy läuft nicht – die IDE braucht ihn"
  [ide_disabled]="IDE deaktiviert – start/stop/restart lassen sie aus; wieder an: nimctl ide"
  [ide_ws]="Projektordner in der IDE: %s" [ide_no_dir]="kein Ordner: %s" [ide_tools]="Shell-Werkzeug für Continue: %s (MCP-Server shell, Werkzeug run)"
  [ide_tools_hint]="einmalig je Browser: Continue-Zahnrad → Tools → shell → run auf Automatic, RunTerminalCommand auf Excluded"
  [ide_mcp_warm]="bereite Shell-Werkzeug vor (Python-Paket mcp) … " [ide_mcp_no_uv]="uv fehlt – das Shell-Werkzeug läuft mit python3 und braucht das Paket mcp"
)
T_en+=(
  [k_v]="IDE" [h_ide]="VS Code in the browser (code-server + Continue) on the proxy: nimctl ide [folder|open [folder]|start|stop|disable|password|config|autocomplete on|off|install]"
  [ide_installing]="installing code-server (~150 MB) … " [ide_ext]="installing extension %s … " [ide_enabled]="IDE enabled – nimctl start starts it too"
  [ide_url]="IDE: http://localhost:%s  · password: nimctl ide password" [ide_pw_reset]="new IDE password set – restart: nimctl ide stop && nimctl ide"
  [ide_cfg]="Continue configuration: %s" [ide_cfg_kept]="%s was not written by nimctl – left untouched (nimctl ide config --force overwrites)"
  [ide_ac_on]="autocomplete on (fast model) – careful: many requests per minute on the free tier" [ide_ac_off]="autocomplete off"
  [ide_models]="models in the IDE: code, fast%s – Continue reloads the configuration automatically" [ide_no_proxy]="proxy is not running – the IDE needs it"
  [ide_disabled]="IDE disabled – start/stop/restart leave it out; back on: nimctl ide"
  [ide_ws]="project folder in the IDE: %s" [ide_no_dir]="not a folder: %s" [ide_tools]="shell tool for Continue: %s (MCP server shell, tool run)"
  [ide_tools_hint]="once per browser: Continue gear → Tools → shell → run to Automatic, RunTerminalCommand to Excluded"
  [ide_mcp_warm]="preparing the shell tool (Python package mcp) … " [ide_mcp_no_uv]="uv missing – the shell tool runs with python3 and needs the package mcp"
)
IDE_MARK="# generated by nimctl"
ide_continue_dir() { printf '%s' "${CONTINUE_GLOBAL_DIR:-$HOME/.continue}"; }
ide_ws_file() { printf '%s' "$NIM_DIR/ide-workspace"; }
ide_workspace() { local d; d=$(cat "$(ide_ws_file)" 2>/dev/null); [[ -n "$d" && -d "$d" ]] && printf '%s' "$d"; }
ide_set_workspace() { # ide_set_workspace <dir> – the folder code-server opens and the shell tool runs in
  [[ -d "$1" ]] || { bad "$(tf ide_no_dir "$1")"; return 64; }
  local d; d=$(realpath_ "$1"); printf '%s\n' "$d" >"$(ide_ws_file)"; info "$(tf ide_ws "$d")"
}
ide_url() { local u="http://localhost:$IDE_PORT" w; w=$(ide_workspace); [[ -n "$w" ]] && u+="/?folder=$(jq -rn --arg d "$w" '$d|@uri')"; printf '%s' "$u"; }
ide_write_shell_tool() { # $NIM_DIR/mcp/shell.py – an MCP server with one tool, `run`, that returns exit code and output
  mkdir -p "$NIM_DIR/mcp"
  cat >"$NIM_DIR/mcp/shell.py" <<'SHELL_TOOL_PY'
#!/usr/bin/env python3
# generated by nimctl – shell tool for Continue in code-server, whose own terminal tool returns no output there
import os, subprocess
try:
    from mcp.server.mcpserver import MCPServer as Server   # mcp >= 2
except ImportError:                                       # mcp 1.x
    from mcp.server.fastmcp import FastMCP as Server

WS_FILE = os.environ.get("NIMCTL_WORKSPACE_FILE", os.path.expanduser("~/.nimctl/ide-workspace"))
MAX_LINES = 300
server = Server("shell", instructions="Runs shell commands in the project folder that is open in the IDE and returns their output.")

def workspace() -> str:
    try:
        d = open(WS_FILE).read().strip()
        if d and os.path.isdir(d):
            return d
    except OSError:
        pass
    return os.path.expanduser("~")

@server.tool()
def run(command: str, cwd: str = "", timeout: int = 900) -> str:
    """Run a bash command and return its exit code and output. cwd defaults to the project folder open in the IDE."""
    d = cwd or workspace()
    if not os.path.isdir(d):
        return f"exit=1\ncwd not found: {d}"
    try:
        p = subprocess.run(["bash", "-lc", command], cwd=d, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return f"exit=124\ntimeout after {timeout}s: {command}"
    out = p.stdout + ("\n[stderr]\n" + p.stderr if p.stderr.strip() else "")
    lines = out.splitlines()
    if len(lines) > MAX_LINES:
        out = f"[{len(lines) - MAX_LINES} earlier lines omitted]\n" + "\n".join(lines[-MAX_LINES:])
    return f"exit={p.returncode}\ncwd={d}\n{out}"

if __name__ == "__main__":
    server.run(transport="stdio")
SHELL_TOOL_PY
  chmod 700 "$NIM_DIR/mcp"
}
ide_write_settings() { # code-server user settings, written once: no welcome page, bash terminal, no telemetry
  local f="$NIM_DIR/ide-data/User/settings.json"; [[ -f "$f" ]] && return 0; mkdir -p "$NIM_DIR/ide-data/User"
  printf '{\n  "workbench.startupEditor": "none",\n  "terminal.integrated.defaultProfile.linux": "bash",\n  "telemetry.telemetryLevel": "off",\n  "continue.telemetryEnabled": false\n}\n' >"$f"
}
ide_warm_mcp() { # fetch the Python package mcp once so the first tool call in the IDE does not wait for a download
  has uv || return 0; [[ -f "$NIM_DIR/mcp/.ready" ]] && return 0
  printf "  %s" "$(t ide_mcp_warm)"
  if uv run --with mcp python -c 'import mcp' >"$LOG_DIR/mcp-warm.log" 2>&1; then printf "%s\n" "$OK"; touch "$NIM_DIR/mcp/.ready"; else printf "%s\n" "$NO"; warn "$(tf inst_fail mcp) → $LOG_DIR/mcp-warm.log"; fi
}
ide_write_config() { # ide_write_config [--force] – code-server.yaml, settings, shell tool (always); Continue's config.yaml (ours or absent)
  mkdir -p "$NIM_DIR/ide-data/extensions"
  printf 'bind-addr: %s:%s\nauth: password\npassword: %s\ncert: false\n' "$BIND" "$IDE_PORT" "$IDE_PASSWORD" >"$NIM_DIR/code-server.yaml.tmp"
  chmod 600 "$NIM_DIR/code-server.yaml.tmp"; mv "$NIM_DIR/code-server.yaml.tmp" "$NIM_DIR/code-server.yaml"
  ide_write_settings; ide_write_shell_tool
  local dir f base="http://127.0.0.1:$PROXY_PORT/v1"; dir=$(ide_continue_dir); f="$dir/config.yaml"; [[ -d "$dir" ]] || { mkdir -p "$dir"; chmod 700 "$dir"; }
  if [[ -f "$f" && "${1:-}" != --force ]] && ! grep -qF "$IDE_MARK" "$f"; then info "$(tf ide_cfg_kept "$f")"; return 0; fi
  local ctx="${NIMCTL_IDE_CONTEXT:-32768}" more="" tool="$NIM_DIR/mcp/shell.py" cmd args
  if has uv; then cmd=$(command -v uv); args=$(jq -cn --arg t "$tool" '["run","--with","mcp","python",$t]')
  else cmd=python3; args=$(jq -cn --arg t "$tool" '[$t]'); info "$(t ide_mcp_no_uv)"; fi
  {
    printf '%s – rewritten on every `nimctl ide` start; remove this line to keep your own edits\nname: nimctl\nversion: 1.0.0\nschema: v1\nmodels:\n' "$IDE_MARK"
    printf '  - name: "code · %s"\n    provider: openai\n    model: nim-code\n    apiBase: %s\n    apiKey: %s\n    roles: [chat, edit, apply]\n    capabilities: [tool_use]\n    defaultCompletionOptions: { contextLength: %s, maxTokens: 8192 }\n' "$MODEL_CODE" "$base" "$MASTER_KEY" "$ctx"
    printf '  - name: "fast · %s"\n    provider: openai\n    model: nim-fast\n    apiBase: %s\n    apiKey: %s\n    roles: [chat]\n    defaultCompletionOptions: { contextLength: %s, maxTokens: 4096 }\n' "$MODEL_FAST" "$base" "$MASTER_KEY" "$ctx"
    if [[ -n "$MODEL_REVIEW" ]]; then more=", review"
      printf '  - name: "review · %s"\n    provider: openai\n    model: nim-review\n    apiBase: %s\n    apiKey: %s\n    roles: [chat]\n    capabilities: [tool_use]\n    defaultCompletionOptions: { contextLength: %s, maxTokens: 8192 }\n' "$MODEL_REVIEW" "$base" "$MASTER_KEY" "$ctx"; fi
    if [[ "$IDE_AUTOCOMPLETE" == 1 ]]; then more+=", autocomplete"
      printf '  - name: "autocomplete · %s"\n    provider: openai\n    model: nim-fast\n    apiBase: %s\n    apiKey: %s\n    roles: [autocomplete]\n    useLegacyCompletionsEndpoint: false\n    autocompleteOptions: { debounceDelay: 500, maxPromptTokens: 1024, onlyMyCode: true }\n' "$MODEL_FAST" "$base" "$MASTER_KEY"; fi
    printf 'context:\n  - provider: code\n  - provider: currentFile\n  - provider: open\n  - provider: diff\n  - provider: terminal\n  - provider: problems\n  - provider: folder\n'
    printf 'mcpServers:\n  - name: shell\n    command: %s\n    args: %s\n    env: { NIMCTL_WORKSPACE_FILE: %s }\n' "$(jq -n --arg s "$cmd" '$s')" "$args" "$(jq -n --arg s "$(ide_ws_file)" '$s')"
    printf 'rules:\n  - name: nimctl shell tool\n    rule: "Run every shell command with the MCP tool run from the server shell: it executes in the project folder open in the IDE and returns the exit code and the output. Never use RunTerminalCommand in this IDE, it returns no output here. Read the exit code before deciding anything; exit=0 means success."\n'
  } >"$f.tmp"; chmod 600 "$f.tmp"; mv "$f.tmp" "$f"
  info "$(tf ide_cfg "$f")"; info "$(tf ide_models "$more")"; info "$(tf ide_tools "$tool")"
}
inst_codeserver() { # standalone install into ~/.local plus the Continue extension (and NIMCTL_IDE_EXTENSIONS)
  mkdir -p "$NIM_DIR/ide-data/extensions"
  if ! has code-server; then
    printf "  %s" "$(t ide_installing)"
    if curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix="$HOME/.local" >"$LOG_DIR/code-server-install.log" 2>&1; then printf "%s\n" "$OK"; else printf "%s\n" "$NO"; bad "$(tf inst_fail code-server) → $LOG_DIR/code-server-install.log"; return 1; fi
    if ! has code-server; then local b; b=$(ls -d "$HOME/.local/lib"/code-server-*/bin/code-server 2>/dev/null | tail -n1); [[ -n "$b" ]] && { mkdir -p "$HOME/.local/bin"; ln -sf "$b" "$HOME/.local/bin/code-server"; }; fi
    has code-server || { bad "$(tf inst_fail code-server)"; return 1; }
  fi
  local ext; for ext in Continue.continue ${NIMCTL_IDE_EXTENSIONS:-}; do
    printf "  %s" "$(tf ide_ext "$ext")"
    if code-server --extensions-dir "$NIM_DIR/ide-data/extensions" --user-data-dir "$NIM_DIR/ide-data" --install-extension "$ext" >>"$LOG_DIR/code-server-install.log" 2>&1; then printf "%s\n" "$OK"; else printf "%s\n" "$NO"; warn "$(tf inst_fail "$ext") → $LOG_DIR/code-server-install.log"; fi
  done
  declare -F inst_uv >/dev/null && ! has uv && inst_uv
  mkdir -p "$NIM_DIR/mcp"; ide_warm_mcp
  [[ -n "$IDE_PASSWORD" ]] || IDE_PASSWORD=$(gen_secret | head -c 24)
  IDE_ENABLED=1; save_conf; ok "$(t ide_enabled)"
}
ide_ensure() { # installed, proxy up, code-server up – and only then enabled for start/stop/restart and systemd
  has code-server || { bad "$(tf svc_missing code-server)"; info "→ nimctl ide install"; return 1; }
  svc_running proxy || { info "$(t proxy_starting)"; start_proxy || { bad "$(t ide_no_proxy)"; return 1; }; }
  mkdir -p "$NIM_DIR/mcp"; ide_warm_mcp
  svc_running ide || start_ide || return 1
  [[ "$IDE_ENABLED" == 1 ]] || { IDE_ENABLED=1; save_conf; }
}
ide_open() { # ide_open [dir] – folder argument wins, then the git project in the current directory, then the stored folder
  if [[ -n "${1:-}" ]]; then ide_set_workspace "$1" || return $?
  elif [[ -d "$PWD/.git" ]]; then ide_set_workspace "$PWD" || return $?
  elif [[ -n "$(ide_workspace)" ]]; then info "$(tf ide_ws "$(ide_workspace)")"; fi
  ide_ensure || return 1; ok "$(tf ide_url "$IDE_PORT")"
  open_url "$(ide_url)" || info "→ $(ide_url)"; info "$(t ide_tools_hint)"
}
ide_disable() { # stop it, take it out of start/stop/restart and systemd; the installation and the configs stay
  if has systemctl && [[ -f "$(unit_dir)/nimctl-ide.service" ]]; then systemctl --user disable --now nimctl-ide 2>/dev/null; rm -f "$(unit_dir)/nimctl-ide.service"; systemctl --user daemon-reload 2>/dev/null; fi
  stop_svc ide; IDE_ENABLED=0; save_conf; ok "$(t ide_disabled)"
}
cmd_ide() { # cmd_ide [dir|open [dir]|start|stop|disable|password [--reset]|config [--force]|autocomplete on|off|install]
  local sub="${1:-open}"; (( $# )) && shift
  [[ "$sub" != open && -d "$sub" ]] && { set -- "$sub" "$@"; sub=open; }   # nimctl ide ~/src/project
  case "$sub" in
    install) inst_codeserver;;
    open)    ide_open "${1:-}";;
    start)   ide_ensure;;
    stop)    stop_svc ide;;
    disable) ide_disable;;
    password) if [[ "${1:-}" == --reset ]]; then IDE_PASSWORD=$(gen_secret | head -c 24); save_conf; ide_write_config >/dev/null; ok "$(t ide_pw_reset)"; fi
              [[ -n "$IDE_PASSWORD" ]] || { IDE_PASSWORD=$(gen_secret | head -c 24); save_conf; }; printf '%s\n' "$IDE_PASSWORD";;
    config)  [[ -n "$IDE_PASSWORD" ]] || { IDE_PASSWORD=$(gen_secret | head -c 24); save_conf; }; ide_write_config "${1:-}";;
    autocomplete) case "${1:-}" in on) IDE_AUTOCOMPLETE=1; save_conf; ide_write_config && warn "$(t ide_ac_on)";; off) IDE_AUTOCOMPLETE=0; save_conf; ide_write_config && ok "$(t ide_ac_off)";; *) bad "$(t invalid): ${1:-}"; return 64;; esac;;
    *) bad "$(t unknown): $sub"; return 64;;
  esac
}
dash_register v cmd_ide k_v use
